/** Substrings that identify national chain / corporate restaurant locations. */
export const CHAIN_NAME_PATTERNS = [
  "kentucky fried chicken",
  "mcdonald",
  "burger king",
  "wendy",
  "taco bell",
  "chick-fil-a",
  "chick fil a",
  "popeyes",
  "pizza hut",
  "domino",
  "papa john",
  "jack in the box",
  "panda express",
  "raising cane",
  "church's chicken",
  "el pollo loco",
  "dairy queen",
  "a&w",
  "a & w",
  "subway",
  "starbucks",
  "dunkin",
  "chipotle",
  "sonic drive",
  "whataburger",
  "in-n-out",
  "five guys",
  "shake shack",
  "buffalo wild wings",
  "olive garden",
  "applebee",
  "ihop",
  "denny",
  "waffle house",
  "cracker barrel",
  "arby",
  "little caesar",
  "tropical smoothie",
  "jamba juice",
  "sweetgreen",
  "wingstop",
  "qdoba",
  "del taco",
  "culver",
  "hardee",
  "carl's jr",
  "habit burger",
  "smashburger",
  "fatburger",
  "baskin robbins",
  "cold stone",
  "ben & jerry",
  "panera",
  "cheesecake factory",
  "red lobster",
  "outback",
  "red robin",
  "pf chang",
  "mod pizza",
  "blaze pizza",
  "jersey mike",
  "jimmy john",
  "firehouse sub",
  "moe's southwest",
  "long john silver",
  "white castle",
  "zaxby",
  "bojangles",
  "captain d",
  "steak 'n shake",
  "checkers",
  "rally's",
  "rodizio",
  "ted's montana",
  "teds montana",
  "fogo de chao",
  "fogo de chão",
  "texas de brazil",
  "longhorn steakhouse",
  "texas roadhouse",
  "golden corral",
  "yard house",
  "bj's restaurant",
  "bjs restaurant",
  "bj's brewhouse",
  "true food kitchen",
  "north italia",
  "cooper's hawk",
  "coopers hawk",
  "benihana",
  "lazy dog",
  "black bear diner",
  "snooze",
  "ruth's chris",
  "morton's",
  "capital grille",
  "melting pot",
  "hooters",
  "twin peaks",
  "seasons 52",
  "bonefish grill",
  "carrabba",
  "maggiano",
  "legal sea food",
  "eddie v",
  "del frisco",
  "mastro",
  "nando's",
  "bahama breeze",
  "california pizza kitchen",
  "hard rock cafe",
  "dave & buster",
  "dave and buster",
  // Convenience / gas-station marts
  "7-eleven",
  "7 eleven",
  "circle k",
  "ampm",
  "am pm",
  "wawa",
  "sheetz",
  "racetrac",
  "kwik trip",
  "casey's",
  "caseys general",
  "royal farms",
  "speedway",
  "quiktrip",
  "cumberland farms",
  "kum & go",
  "flying j",
  "pilot travel",
];

/** SQL fragment + values for excluding chain, fast-food, and franchise-group leads. */
export function chainLocationExcludeClause(startIdx: number): {
  sql: string;
  values: string[];
} {
  const patterns = CHAIN_NAME_PATTERNS.map((p) => `%${p}%`);
  const nameChecks = patterns.map((_, i) => `business_name ilike $${startIdx + i}`).join(" or ");
  return {
    sql: `(
      coalesce(lead_type, 'location') <> 'franchise_group'
      and not (place_types && ARRAY['fast_food_restaurant']::text[])
      and not (place_types && ARRAY['convenience_store']::text[])
      and not (${nameChecks})
    )`,
    values: patterns,
  };
}
